CFLAGS = -Wall -g

all: ex1 ex3 ex4 ex5

ex1:
	clang $(CFLAGS) ex1.c -o ex1

ex3:
	clang $(CFLAGS) ex3.c -o ex3

ex4:
	cc $(CFLAGS) ex4.c -o ex4

ex5:
	clang $(CFLAGS) ex5.c -o ex5

clean:
	rm -f ex1 ex3 ex4

.PHONY: all clean